title: where we blog about our camping trips
email: m@cto.hiv
description: > # Markus and Tanja blog about their camping trips
baseurl: "/camping.cto.hiv" # the subpath of your site, e.g. /blog/
url: "https://coderbyheart.github.io"
twitter_username: coderbyheart
github_username:  coderbyheart

# Build settings
markdown: kramdown
