title: Markus und Tanja bloggen über ihren Camping-Urlaub
email: m@cto.hiv
description: > # Markus und Tanja bloggen über ihren Camping-Urlaub
baseurl: "/camping.cto.hiv" # the subpath of your site, e.g. /blog/
url: "https://coderbyheart.github.io"
twitter_username: coderbyheart
github_username:  coderbyheart
timezone: Europe/Berlin

# Build settings
markdown: kramdown

include: ['tracks']
